server:
  port: 8081
spring:
  application:
    name: course-list
  datasource:
    url: jdbc:mysql://115.159.98.172:3306/crush?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username:
    password:
#logging:
# pattern:
#   console: %clr(%d{${LOG_DATEFORMAT_PATTTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
